
variables:
  websiteManifestName: 'websitemanifest'
  kubeconfigArtifactName: 'kubeconfig'

stages:

      
  - stage: ProvisionEnvironment
    displayName: Provision Env with Terraform
    variables:
      - group: 'Terraform'
  
    jobs:
    - job: TransformConfiguration
      pool:      
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace tokens in **/*.tfvars'
        inputs:
          rootDirectory: ./env         
          targetFiles: '**/*.tfvars'


      - script: |
          terraform init \
            -backend-config="resource_group_name=$(tf-backend-resource-group)" \
            -backend-config="storage_account_name=$(tf-backend-storage-account)" \
            -backend-config="container_name=$(tf-backend-container-name)" \
            -backend-config="key=$(tf-backend-state-file-name)" \
            -backend-config="access_key=$(tf-backend-state-file-key)"
    
        workingDirectory: ./env
        displayName: 'Terraform init'
  
      - script: terraform apply -auto-approve -var-file="terraform.tfvars"
      
        workingDirectory: ./env
        displayName: 'Terraform apply'
